version: 0.2

phases:
  install:
    commands:
      - echo "Installing required software"
      - pip install -r hello_world/requirements.txt
      - pip install aws-sam-cli
  pre_build:
    commands:
      - echo "Running tests"
  #      - pytest tests/

  build:
    commands:
      - echo "Building the application"
      - sam build
      - sam package --output-template-file packaged.yaml --s3-bucket $S3_BUCKET # S3_BUCKET is specified in CodeBuild in AWS

artifacts:
  files:
    - packaged.yaml
