version: 0.2

phases:
  install:
    commands:
      - echo "Installing required software"
      - pip install -r hello_world/requirements.txt
      - pip install aws-sam-cli
      - echo "Installing pytest"
      - python -m pip install pytest

  build:
    commands:
      - echo "Running unit tests"
      - python -m pytest tests/unit/test_math_functions.py
      - echo "Building the application"
      - sam build
      - sam package --output-template-file packaged.yaml --resolve-s3 --template-file template.yaml

artifacts:
  files:
    - packaged.yaml
